### ISSUE TITLE
Зачем Продуктивное хранилище (2-ое хранилище)?

### ISSUE THREAD

**Issue by zeegin** [arkuznetsov/some1cdocs#1]
Почему вместо **Продуктивное хранилище (2-ое хранилище)** не используется сборка поставки из **Централизованное хранилище разработки (1-ое хранилище)**?

Ведь поставить на полную поддержку базы *QA_\** и *PRD_\** и обновлять их автоматически или полуавтоматически (по запросу) это проще?

**Comment by arkuznetsov** [comment]
@zeegin Не имею ничего против деплоя поставкой, но вариант с хранилищем для меня оказывается более удобным:
1. потому, что и в "боевой" системе присутствует информация о поддержке от вендора.
2. накатывание hot-fix

нужно учитывать, что документ существует со времен 8.1.

а некоторые живут еще с 3-мя хранилищами (отдельно для тестовых баз). :-)

**Comment by zeegin** [comment]
Просто сама схема организации очень хорошо продумана.
Но переносить из хранилища в хранилище - это кажется очень трудозатратно.

**Comment by arkuznetsov** [comment]
@zeegin А для этого есть скрипты! :-)
